title : PageNote 's Blog
tagline: 互联网 知识管理 Note
author :
  name : aboleab
  email : aboleab@gmail.com
  github : aboleab
  twitter : aboleab
  feedburner : aboleab

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
